/**
 * Utility functions for module implementations
 */

/**
 * Create a namespaced internal node ID for a module.
 * Format: {moduleId}:{internalId}
 *
 * Internal nodes generated by module expansion are namespaced with the
 * module instance ID to avoid naming conflicts.
 *
 * @param moduleId - The module instance ID
 * @param internalId - The internal node's local ID
 * @returns Namespaced node ID
 */
export function createInternalId(moduleId: string, internalId: string): string {
  return `${moduleId}:${internalId}`;
}
